version: "3.8"

services:
  backend:
    image: velesstan/backend:stage
    restart: always
    env_file:
      - app.env
    ports:
      - 5000:5000 # Outside : Inside
    depends_on:
      - database

  database:
    image: mongo:4.4.13
    restart: always
    volumes:
      - ./mongod.conf:/etc/mongod.conf
      - ./mongodb:/data/db
    command: mongod --config /etc/mongod.conf
    env_file:
      - app.env
    ports:
      - "27017:27017"
