name: Code quality

on:
  pull_request:

jobs:
  unit-tests:
    name: Unit tests
    environment: Stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 17.x

      - name: Install packages and run unit tests
        run: |
          npm install
          npm run test
